### PR TITLE
Fileutil improvements

### PR DESCRIPTION
**Pull request by meejah**
This pulls out (most of) the fileutil.py changes from 2438.magic-folder-stable.14

### CODE REVIEW

**Comment by warner** [comment]
I don't pretend to understand the problem, but the new test failed on appveyor (windows).. could you take a look?

  https://ci.appveyor.com/project/tahoe-lafs/tahoe-lafs/build/1.0.80#L1129

```
File "c:\projects\tahoe-lafs\src\allmydata\test\test_util.py", line 575, in test_make_dirs_with_absolute_mode
    new_mode = os.stat(os.path.join(workdir,"a/b/c/d")).st_mode & 0777
exceptions.WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: u'\\\\?\\C:\\projects\\tahoe-lafs\\_trial_temp\\test_make_dirs_with_absolute_mode\\a/b/c/d'
```

**Comment by meejah** [comment]
hmm, presumably needs some other windows-fixes patch brought in. i will find it :)

**Comment by meejah** [comment]
Hmmm. I didn't really change anything in the last push (just squashed two windows-fixup commits together to force a build). Perhaps similar to an intermittent problem @warner was seeing?

**Comment by warner** [comment]
Eh, appveyor seems happy with the latest version, and that's good enough for me. I'll rebase to current master (some storage-broker stuff changed since then) and land it shortly. Thanks!

**Comment by warner** [comment]
Landed (in rebased form) in c715e0d.

**Pull request closed without merging**
