### PR TITLE
4143: Refresh docker images for builders

### PR DESCRIPTION
**Pull request by btlogy**
Part of ticket:[4143](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/4143) to refresh images

Initially, we wanted to update the current images and add new ones (`debian-12` and `ubuntu-24.04`)at once because the operation involves click-ops.

However, we've discovered a problem with `gpgme-config` on those new images (no longer part of `gpgme-dev` package).
Thus, this PR is only about the current images + `fedora-40` (which still does provide the `gpgme-config` tool).

Once published, I will PR an other change to use those new images as builders and retire `fedora-35` and `ubuntu-20.04`.

### CODE REVIEW

**Comment by btlogy** [comment]
@meejah this PR should be ready (soon) to be used to publish new images on Docker Hub.

**Comment by meejah** [comment]
`Job was rejected because this version of Docker is not supported on this resource class. Try removing the version of Docker in your .circleci/config.yml and re-running `

**Comment by btlogy** [comment]
> `Job was rejected because this version of Docker is not supported on this resource class. Try removing the version of Docker in your .circleci/config.yml and re-running`

Something has been deprecated:

https://discuss.circleci.com/t/remote-docker-image-deprecations-and-eol-for-2024/50176

We can no longer pin the version of docker as we previously did here:

https://github.com/tahoe-lafs/tahoe-lafs/blob/dc6ea19d9697a4e95cf8cad999205ec7d0ac6843/.circleci/config.yml#L615-L616

This is fixed in a461590.

**Comment by btlogy** [comment]
Passed that Docker error, the jobs are all broken by a new dependency introduced by #1395.

Here is what we get now when we try to rebuild `debian-11` for instance (the error is identical for the other images):

```
   × python setup.py egg_info did not run successfully.
   │ exit code: 1
   ╰─> [1 lines of output]
       Could not find gpgme-config.  Please install the libgpgme development package.
       [end of output]
```

This new dependency can be provided by adding `libgpgme-dev` (on Debian likes) or `gpgme-devel` (on Fedora like) packages.
I've added those in 12f9917.

**Comment by btlogy** [comment]
However, it seems like this `gpgme-config` tool has been removed from [gpgme](https://www.gnupg.org/documentation/manuals/gpgme/Building-the-Source.html) (somewhere between 1.16.0 and 1.18.0):

> In the past, gpgme used to ship with a small helper program gpgme-config. This functionality of gpgme-config is replaced by pkg-config with gpgme.pc file.

This has apparently triggered a few bug-fixes in `debian-12` which ships `libgpgme-dev-1.18.0-3+b1` (instead of `libgpgme-dev-1.14.0-1+b2` in `debian-11`):

https://bugs.debian.org/cgi-bin/pkgreport.cgi?tag=gpgme-config-transition;users=pkg-gnupg-maint@lists.alioth.debian.org

I'm not sure when/if `fedora` and `oraclelinux` will hit this, but what I see is that we can not build `debian-12` nor `ubuntu-24.04` images since #1395 because they both provide `libgpgme-dev-1.18.0` (and there were successfully built before hatchling).

Does this mean tahoe-lafs can no longer be installed on `debian-12` and `ubuntu-24.04` since it uses hatchling?
I hope not, but we were unfortunately not testing those yet and it will require more work to find out.

In the meantime, I'm going to remove those 2 images from this PR and work on them separately, so we can move on a step further.

**Comment by btlogy** [comment]
A bit more on why the master branch can pass the unit tests on `debian-11` and `ubuntu-2x.04` builders while they are missing the new `gpgme devel` packages:

On `debian-11` for instance, the tests are started with this command:

```
tox -c /tmp/project/tox.ini --workdir /tmp/tahoe-lafs.tox --notest -e 39
```

And this command dos not seem to require the `gpg` module (nor the `dulwich` one).
While the `prepare-image.sh` script needs them when it calls this command:

```
pip wheel --wheel-dir /tmp/wheelhouse '/tmp/project[testenv]' '/tmp/project[test]' '/tmp/project[build]'
```

@meejah : could this means we can still use and test tahoe-lafs on those distro's but no longer build it w/o this new `gpgme` dependency?

**Comment by btlogy** [comment]
> In the meantime, I'm going to remove those 2 images from this PR and work on them separately, so we can move on a step further.

Done in f80ac6f.

@meejah: could you please try to manually trigger the build again with what's left of those images in `pull/1409`?

**Comment by meejah** [comment]
> Ok, now I see: this new extra build has been introduced in https://github.com/tahoe-lafs/tahoe-lafs/commit/53451abef48c9ed72bf4a839fceb63b1284557b2

That doesn't seem to link to a relevant commit.

> Does this mean tahoe-lafs can no longer be installed on debian-12 and ubuntu-24.04 since it uses hatchling?

No.
You only need the `build` extra to produce wheels, and you only need the gpg stuff to sign tags / releases.
Debian and Ubuntu users should be installing a wheel.

**Comment by btlogy** [comment]
> > Ok, now I see: this new extra build has been introduced in [53451ab](https://github.com/tahoe-lafs/tahoe-lafs/commit/53451abef48c9ed72bf4a839fceb63b1284557b2)
> 
> That doesn't seem to link to a relevant commit.
> 
> > Does this mean tahoe-lafs can no longer be installed on debian-12 and ubuntu-24.04 since it uses hatchling?
> 
> No. You only need the `build` extra to produce wheels, and you only need the gpg stuff to sign tags / releases. Debian and Ubuntu users should be installing a wheel.

Got it.

So we do not need the gpg stuff in our CI today.
Maybe we could find a way to workaround while the breaking change get a fix (I do not see much happening in https://pypi.org/project/gpg, assuming the `gpgme-config` is called from this module!?).

**Comment by meejah** [comment]
>  Maybe we could find a way to workaround while the breaking change get a fix

I'm not sure what you're referring to here. I can `pip install tahoe-lafs[build]` locally (nobody else should need `gpg` nor `dulwich`).

**Comment by meejah** [comment]
> > Ok, now I see: this new extra build has been introduced in https://github.com/tahoe-lafs/tahoe-lafs/commit/53451abef48c9ed72bf4a839fceb63b1284557b2
> 
> That doesn't seem to link to a relevant commit.

Regardless the 'build' extra can (should?) be removed esp if causing issues

**Comment by btlogy** [comment]
> > Ok, now I see: this new extra build has been introduced in [53451ab](https://github.com/tahoe-lafs/tahoe-lafs/commit/53451abef48c9ed72bf4a839fceb63b1284557b2)
> 
> That doesn't seem to link to a relevant commit.

My bad. Hasty copy/paste I'm afraid.
I meant this one: f5e80f2f6ffbc617f1f2a2ddf2209b9e79308343

**Comment by btlogy** [comment]
@meejah I see you've triggered the `build-images` workflow. Thank you.

Good news: 5 out of 6 images were built and published.
Bad news: the failed one is `oraclelinux-8`:

```
Error: Unable to find a match: gpgme-devel
```

I was wrongly assuming this distro would have the same package as the `fedora` ones.
I should have tested this more thoroughly.
Let's hope it just another name: testing locally...

**Comment by btlogy** [comment]
If/when this gives us 6/6 new published images, I suggest we merge this PR and I'll prepare a new one to (re-)enable the (new) builders.

**Comment by btlogy** [comment]
> Commit [144b2cb](https://github.com/tahoe-lafs/tahoe-lafs/commit/144b2cbc86d4c5fa417780ffe213243d3cb4a079) should fix this.

Oups: this commit is not in the branch! Fixing this...

**Comment by btlogy** [comment]
The integration test on `ubuntu-20.04` and `python-3.21` on GHA is running for more than 3 hours!
I can not stop, nor rebuild it.

I suppose only @meejah can.

**Comment by meejah** [comment]
> @meejah I see you've triggered the `build-images` workflow. Thank you.
> 
> Good news: 5 out of 6 images were built and published.
> Bad news: the failed one is `oraclelinux-8`:
> 
> ```
> Error: Unable to find a match: gpgme-devel
> ```


You do not need this. Remove the 'build' extra.

**Comment by btlogy** [comment]
> > @meejah I see you've triggered the `build-images` workflow. Thank you.
> > Good news: 5 out of 6 images were built and published.
> > Bad news: the failed one is `oraclelinux-8`:
> > ```
> > Error: Unable to find a match: gpgme-devel
> > ```
> 
> You do not need this. Remove the 'build' extra.

It's a bit too late for that: the work has been done and it's already in all those images because we had to adapt to this commit f5e80f2f from #1395.

Even the master branch has already built successfully with this new `gpgme` dependency baked in.

Also, with what I've just learned a bit from #1403, I'm now wondering if reverting this commit would also remove `hatchling` and `hatch-vcs` wheels and break the build.

https://github.com/tahoe-lafs/tahoe-lafs/blob/e8ddd8a0d96fb761bd3e0eddadd56ac6bc6f7b3b/pyproject.toml#L203-L208

Maybe we "do not need this" as you say, but in my opinion, removing this dependency is not part of the scope of this present PR and [ticket:4143](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/4143).

I would rather prepare a new PR to remove it properly in the scope of [ticket:4133](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/4143) for which has been introduced.
I do now now what would be the best course for that new PR, but maybe we could split this `build` extra into more sections (e.g.: `build` and `release`)?

What I'm sure is that we will need to verify locally a lot before publishing new images :angry:
BTW: I'm thinking to improve this process by building those images on PR (I'll elaborate in [ticket:3484](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/3484)).

Of course, at the end, it's up to you @meejah: feel free to tweak this PR to your liking.

**Comment by btlogy** [comment]
Sorry. I made a boubouh by forcing push here while it was meant for my test branch in the LA fork...
Anyway...

It seems like @meejah has merged something that would remove this dependency on `gpgme` in #1411.

So I've merged this back here and tried to revert the changes introduced for this new dependency (12f99171c and 8f753c0de) to see if we could build the images once again the way they were before #1395.

And they seem to do just [fine](https://app.circleci.com/pipelines/github/tahoe-lafs/tahoe-lafs/5272/workflows/a6bda041-01db-4567-ba12-819530acfe13).
So I'm just reverting my tweak to build the images w/o publishing (fad078103 will be part of a separate PR for [ticket:3484](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/3484)) and the PR should look better.

A lot of work for not much...

**Comment by meejah** [comment]
Instead of reverting and making twice as many commits you can just get rid of the commits (like https://github.com/tahoe-lafs/tahoe-lafs/pull/1418), especially if you're force-pushing the branch regardless.

I took your "feel free to tweak this PR to your liking" comment to mean you weren't going to continue this PR.

**Comment by btlogy** [comment]
> Instead of reverting and making twice as many commits you can just get rid of the commits (like #1418), especially if you're force-pushing the branch regardless.

The force-pushed was not intended. Sorry for that.

I've chosen to explicitly revert because:

1. it keeps a commit (8f753c0de - not lost in the force-push) defining the images as they are currently used by any other PR's introduced since yesterday and will be untill you publish the new ones (so we have reproducibility if we need it),
2. and it also reflects the sad history of this PR which could have be merged as it is now before just #1395.

> I took your "feel free to tweak this PR to your liking" comment to mean you weren't going to continue this PR.

And I though you could push on top of pull branches, but I'm not so sure now.
I would certainly not continue to work on this w/ the imperative tone you were using yesterday.

But thank you for #1411. I hope things are now back on track.

**Comment by meejah** [comment]
>  I would certainly not continue to work on this w/ the imperative tone you were using yesterday.

I don't know what this means.

**Comment by meejah** [comment]
> and it also reflects the sad history of this PR which could have be merged as it is now before just https://github.com/tahoe-lafs/tahoe-lafs/pull/1395.

What??

**Comment by btlogy** [comment]
> > and it also reflects the sad history of this PR which could have be merged as it is now before just #1395.
> 
> What??

I had to adapt this work to a moving target: a lot of work for result of a few lines.
It does not feel great to work this way.
So yes, I find it sad.

**Comment by meejah** [comment]
>  So yes, I find it sad.

Instead of taking my advice several days ago to remove a single line that would have eliminated much of this work, you instead chose to argue about it across several mediums. In the end I had to do it anyway. I also found this to be "not great".

Work has continued in https://github.com/tahoe-lafs/tahoe-lafs/pull/1418 which is the future here, since it includes changes to install Tor from proper upstream and uses Debian 12 / "stable" (instead of "oldstable"). Regardless, existing images are built from (a previous copy of) that branch.

**Comment by btlogy** [comment]
At least half of you new PR is inline with the scope of this [ticket:4143](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/4143).
Congratulation @meejah

**Comment by meejah** [comment]
> At least half of you new PR is inline with the scope of this [ticket:4143](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/4143).

I do not understand what you mean..?

**Comment by meejah** [comment]
I don't know what Least Authority is doing these days and "tone" in text can be hard: @btlogy if you're upset about any of this you need to please reach out via email, or IRC or schedule a video chat. My only goal here was/is to have working build-system (for downstream) and working CI (to move other PRs forward).

**Comment by btlogy** [comment]
> I don't have any insight into what Least Authority is doing these days

What we at Least Authority are doing is:
1. detailed in Trac tickets,
2. extensively discussed in nearly every N&B (you were attending the [last one](https://hackmd.io/DzedQERvRLWaaaeo-gtDhA#Dec-10-2024) where we've discussed the creation of this ticket),
3. summarized in the monthly update posted on the mailing list (e.g.: [Least Authority November Update](https://lists.tahoe-lafs.org/pipermail/tahoe-dev/2024-December/010107.html))

Please reach out to it author of the last item if we are not using the proper channel, or not correctly the existing ones.

> and "tone" in text can be hard

In my opinion, this is an advice: "Could you try to avoid using imperative sentence?"
While this is would look more like an order: "Do not use imperative sentence."
Both in text.

> @btlogy if you're upset about any of this you need to please reach out via email, or IRC or schedule a video chat.

I've already asked if we could pair on this topic during the last N&B,
then I've proposed to discuss it again in a video meeting on Thu because the frustration was obviously growing.
You've decide to ignored me twice.

In that regards, I've found a possible problem the community may want to fix to improve interactions between contributors: [ticket:4147 Update CoC to document accurate contacts](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/4147).

> My only goal here was/is to have working build-system (for downstream) and working CI (to move other PRs forward).

So was mine.

**Comment by meejah** [comment]
I still do not understand what https://github.com/tahoe-lafs/tahoe-lafs/pull/1409#issuecomment-2542414169 means.

**Comment by meejah** [comment]
> I've already asked if we could pair on this topic during the last N&B, then I've proposed to discuss it again in a video meeting on Thu because the frustration was obviously growing. You've decide to ignored me twice.

It was not my intention to ignore anything, did I miss an email? Or some other invite?

**Comment by meejah** [comment]
Your nick has not been in the IRC channel (at least when I've tried to tab-complete it) for many days, is there some other realtime(-ish) way to communicate?

**Comment by meejah** [comment]
Is the comment you're upset about the one in https://github.com/tahoe-lafs/tahoe-lafs/pull/1409#issuecomment-2539770600 ?

**Pull request closed without merging**
