### PR TITLE
Update license / copyright line in README.rst

### PR DESCRIPTION
**Pull request by hacklschorsch**
Update license/copyright string.

[ticket: 1419](https://github.com/tahoe-lafs/tahoe-lafs/pull/1419).

### CODE REVIEW

**Comment by meejah** [comment]
Needs a ticket / newsfragment ... but also I don't think it's accurate at all :( since there has never been a copyright assignment. So it's probably "Tahoe-LAFS contributors" or similar? (IANAL).

**Comment by hacklschorsch** [comment]
🤷

**Comment by meejah** [comment]
You don't want to update the year at least...?

(I don't know why you closed this).

**Comment by hacklschorsch** [comment]
I thought you didn't like the PR, thus I deleted it.

**Comment by hacklschorsch** [comment]
Maybe giving no end date is fine here too?

**Comment by meejah** [comment]
Not sure. I meant that codechecks wont pass without a newsfragment.

**Comment by meejah** [comment]
Hmm, I thought we'd convinced the circleci/integration builder to be "non-fatal" :thinking:

**Comment by meejah** [comment]
Also filed https://tahoe-lafs.org/trac/tahoe-lafs/ticket/4154#ticket

**Comment by hacklschorsch** [comment]
I stumbled over [ticket #4153](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/4153) I had created for this and saw I accidentally had linked this PR to itself instead, d'uh!  Posting the URL for reference.

**Pull request merged**
