### PR TITLE
1710

### PR DESCRIPTION
**Pull request by meejah**
WIP changes for deletions

### CODE REVIEW

**Comment by daira** [comment]
Reviewing.

**Comment by daira** [comment]
Ah ok, this is the branch we looked at in the pairing with one extra commit. +1 (but let's get it passing before merging it).

**Comment by meejah** [comment]
yes, this is the one from pairing; I'm closing this as I'm going to re-do the PR after squashing + cleanup etc.

**Comment by daira** [comment]
+1

**Pull request closed without merging**
