### PR TITLE
trim usage of to-be-removed "future" library

### PR DESCRIPTION
**Pull request by a-detiste**

### CODE REVIEW

**Comment by a-detiste** [comment]
@merkys

**Comment by meejah** [comment]
Please add a file in `newsfragments/4152.other` with some short text describing the change (e.g. "remote usage of deprecated future library"); this becomes part of the ChangeLog on the next release.

"4152" refers to https://tahoe-lafs.org/trac/tahoe-lafs/ticket/4152 (ticket-tracking is still in Trac).

Thanks! Otherwise looks good to me (the above will make the "codechecks" builder pass).

There are some "sometimes failing" tests still, I will look on the next run to make sure that's what the other failures are :/

**Review by meejah — APPROVED** [review]

**Comment by a-detiste** [comment]
We're reaching the end of this

Heres' what's left to do:

```
pyproject.toml:    "future >= 0.18.2",
misc/simulators/simulate_load.py:from past.builtins import cmp
misc/coding_tools/make-canary-files.py:from past.builtins import cmp
src/allmydata/util/hashutil.py:from past.builtins import chr as byteschr
src/allmydata/util/base62.py:from past.builtins import chr as byteschr
src/allmydata/test/test_base62.py:from past.builtins import chr as byteschr
src/allmydata/test/test_system.py:from past.builtins import chr as byteschr
src/allmydata/test/test_encode.py:from past.builtins import chr as byteschr
src/allmydata/test/common.py:from past.builtins import chr as byteschr
```

Six can be done later.

**Comment by merkys** [comment]
Thanks @a-detiste! It would be great to have `past` trimmed as well.

**Comment by a-detiste** [comment]
> Thanks @a-detiste! It would be great to have `past` trimmed as well.

That was done in the next PR which got merged as well.

**Comment by merkys** [comment]
> That was done in the next PR which got merged as well.

I gather you mean #1421, which I overlooked. Thanks!

**Pull request merged**
