### PR TITLE
WIP: mypy support

### PR DESCRIPTION
**Pull request by jaraco**
https://tahoe-lafs.org/trac/tahoe-lafs/ticket/3399

### CODE REVIEW

**Comment by sajith** [comment]
CircleCI is now failing with a "Could not find context dockerhub-auth" error.  I think CircleCI would run if you create an empty "dockerhub-auth" context, and then re-run the workflow from start.

That is what I did anyway.  Ideally our CircleCI configuration should be able to do unauthenticated pulls from DockerHub when DockerHub credentials are not available.  I have not been able to figure out how to do that.

**Comment by jaraco** [comment]
Thanks sajith - I'm unfamiliar with creating dockerhub-auth contexts. Where would I create an empty one?

**Comment by sajith** [comment]
Log in at https://app.circleci.com, go to "organization settings" (this should be jaraco's organization settings, not tahoe-lafs' organization settings), and then click on the "create context" button to add a "dockerhub-auth" (without quotes, just to be sure!) context.

My understanding is that contexts are used to hold environment variables (such as Docker Hub credentials).  For now our brand new "dockerhub-auth" context doesn't have to contain anything.  At this point, if "re-run workflow" button is in fact able to re-run the workflow without that "could not find context" error, things should be good to go.

Ideally we should not have to go through these steps.  I have filed [3541](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/3541), but I don't know how to make contexts optional.  I guess we could ask in CircleCI forums.

**Comment by wearpants** [comment]
> CircleCI is now failing with a "Could not find context dockerhub-auth" error. I think CircleCI would run if you create an empty "dockerhub-auth" context, and then re-run the workflow from start.

I don't think this is related to mypy, is it? should probably be a separate issue / handle by somebody more familiar with infra (ie, probably not @jaraco)

**Comment by exarkun** [comment]
> > CircleCI is now failing with a "Could not find context dockerhub-auth" error. I think CircleCI would run if you create an empty "dockerhub-auth" context, and then re-run the workflow from start.
> 
> I don't think this is related to mypy, is it? should probably be a separate issue / handle by somebody more familiar with infra (ie, probably not @jaraco)

Correct, it's unrelated to MyPy but it's an issue with this PR because it causes most CI to be unrunnable.  I think setting up the context is pretty easy and sajith gave instructions for doing so - but another solution is to switch to an in-repo branch (which will cause CI to use the in-repo context that already exists).  I think @jaraco has access to do that.

The new context requirement is probably a development workflow regression that we should figure out.  sajith filed a ticket for this - https://tahoe-lafs.org/trac/tahoe-lafs/ticket/3541 - but I'm not sure yet how we're going to resolve it.

**Comment by exarkun** [comment]
> I think @jaraco has access to do that.

Also, notably, *only* @jaraco can create the required context because it has to exist in his GitHub account settings.

**Comment by jaraco** [comment]
> another solution is to switch to an in-repo branch

This approach sounds preferable. I'll plan to do that. Thanks.

**Comment by wearpants** [comment]
>I think @jaraco has access to do that.

thanks for clarifying

**Comment by jaraco** [comment]
Superseded by #915

**Pull request closed without merging**
