### PR TITLE
Add 'api-version' field to JSON result of the deep-stats operation

### PR DESCRIPTION
**Pull request by vrusinov**
For https://tahoe-lafs.org/trac/tahoe-lafs/ticket/567

### CODE REVIEW

**Comment by meejah** [comment]
LGTM, I'm +1 on merging this.

**Comment by vrusinov** [comment]
Are we waiting on something to merge this?

I'm used to working off HEAD, so I'd rather wait until this one is merged before sending more pull requests. Of course I can adapt to different workflow.

**Comment by warner** [comment]
Sorry, I was busy with the 1.12.0 release and also didn't want to land any new code changes during the beta period. I've rebased this to current trunk and will land it after running the tests one more time. Thanks!

**Comment by vrusinov** [comment]
Thanks, understood.

And thanks for the new release!

**Pull request closed without merging**
