### PR TITLE
2804.magic folder web status

### PR DESCRIPTION
**Pull request by meejah**
This puts a simple indicator on the front welcome page. Note that I've based this on the other 2408 PR (#309) so if you merge that one first this one should show only one commit. I think. Or I'll have to rebase it after you merge the other ...

### CODE REVIEW

**Comment by meejah** [comment]
The feature looks like this:

mf-bad
mf-good

**Comment by warner** [comment]
I guess this needs to be rebased now, #309 landed but was rebased first.

**Comment by warner** [comment]
Oh, and should the "successful" case display a "last scan at: XYZ" or "last successful scan at:" message?

**Comment by meejah** [comment]
Okay, rebased and I added timestamps for successful scans too. I also took out the `try/catch` that #309 introduced (the one you wanted to revisit) because it's not required.

**Comment by warner** [comment]
ok, looks good

**Pull request merged**
