### PR TITLE
Make the HTTP version test more robust

### PR DESCRIPTION
**Pull request by itamarst**
Fixes https://tahoe-lafs.org/trac/tahoe-lafs/ticket/3850

(I can't prove this'll fix it, but it seems the likely reason.)

### CODE REVIEW

**Comment by exarkun** [comment]
It looks like there is another varying entry:

```
[FAIL]
Traceback (most recent call last):
  File "/home/exarkun/VirtualEnvs/tahoe-lafs3/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/exarkun/Work/python/tahoe-lafs/src/allmydata/test/test_storage_http.py", line 78, in test_version
    self.assertEqual(version, expected_version)
  File "/home/exarkun/VirtualEnvs/tahoe-lafs3/lib/python3.7/site-packages/twisted/trial/_synctest.py", line 434, in assertEqual
    super(_Assertions, self).assertEqual(first, second, msg)
  File "/nix/store/0n8slcq8p5x31kc9hncabsqq9y3fpkzp-python3-3.7.3/lib/python3.7/unittest/case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/nix/store/0n8slcq8p5x31kc9hncabsqq9y3fpkzp-python3-3.7.3/lib/python3.7/unittest/case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
twisted.trial.unittest.FailTest: {b'ht[83 chars]3867491328, b'maximum-mutable-share-size': 691[249 chars]350'} != {b'ht[83 chars]3867487232, b'maximum-mutable-share-size': 691[249 chars]350'}
  {b'application-version': b'tahoe-lafs/1.16.0.post350',
   b'http://allmydata.org/tahoe/protocols/storage/v1': {b'delete-mutable-shares-with-zero-length-writev': True,
                                                        b'fills-holes-with-zero-bytes': True,
-                                                       b'maximum-immutable-share-size': 13867491328,
?                                                                                              ^^  -

+                                                       b'maximum-immutable-share-size': 13867487232,
?                                                                                              ^^^

                                                        b'maximum-mutable-share-size': 69105000000000000,
                                                        b'prevents-read-past-end-of-share-data': True,
                                                        b'tolerates-immutable-read-overrun': True}}

allmydata.test.test_storage_http.HTTPTests.test_version
```

**Comment by itamarst** [comment]
I didn't bother checking it because it's in all caps so I assumed it's a constant!!!

**Comment by itamarst** [comment]
Oh, misread. It's a duplicate of the other one. Ugh.

**Comment by itamarst** [comment]
OK, fixed that.

**Review by exarkun — APPROVED** [review]
Thanks!

**Pull request merged**
