### PR TITLE
use Resource, not Page for web-status

### PR DESCRIPTION
**Pull request by meejah**

### CODE REVIEW

**Comment by meejah** [comment]
The travis errors looks like it's using the wrong code; line 5961 viewed on github in this branch isn't the line that the stacktrace prints out ... very odd.

**Comment by meejah** [comment]
i changed the commit message slight and re-pushed to see if travis changes its mind...

**Comment by meejah** [comment]
I'm at a loss to explain what's going on here in the Travis builds :(

**Comment by warner** [comment]
LGTM, landed

**Pull request merged**
