### PR TITLE
added instruction for missing dependencies

### PR DESCRIPTION
**Pull request by tpltnt**
Hi there,

three dependencies where missing in the installation instruction, so I added them.

Cheers,
tpltnt

### CODE REVIEW

**Comment by warner** [comment]
Huh.. we shouldn't need any explicit *python* installs. If something needs installing, it should go into `setup.py` (or, in our case, `src/allmydata/_auto_deps.py`). `pip install` should be the One True Way to get everything (python) that you need.

Looking at our dependency graph, I see that those three are dependencies of setuptools. `packaging` is also needed by `cryptography`, and `six` of course is used by several of our upstream dependencies (but not by tahoe itself). So `pip install .` from the tahoe source tree should have picked those up.

What errors did you get without explicitly installing `appdirs` or `packaging` or `six`? Does a `pip install` into a clean virtualenv work?

**Comment by tpltnt** [comment]
Installing into a clean virtualenv does not work. The process complains that `appdirs`, `packaging` and `six` are missing. Here is the example output when following the readme:
```
testmachine% venv/bin/pip install --editable .
Obtaining file:///home/foo/code/tahoe-lafs
  Running setup.py (path:/home/foo/code/tahoe-lafs/setup.py) egg_info for package from file:///home/foo/code/tahoe-lafs
    
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
Downloading/unpacking setuptools>=11.3 (from tahoe-lafs==1.12.1.post9)
  Downloading setuptools-34.3.3-py2.py3-none-any.whl (389kB): 389kB downloaded
Downloading/unpacking zfec>=1.1.0 (from tahoe-lafs==1.12.1.post9)
  Downloading zfec-1.4.24.tar.gz (175kB): 175kB downloaded
  Running setup.py (path:/tmp/pip-build-mX00xZ/zfec/setup.py) egg_info for package zfec
    
Downloading/unpacking zope.interface>=3.6.0,!=3.6.3,!=3.6.4 (from tahoe-lafs==1.12.1.post9)
  Downloading zope.interface-4.3.3.tar.gz (150kB): 150kB downloaded
  Running setup.py (path:/tmp/pip-build-mX00xZ/zope.interface/setup.py) egg_info for package zope.interface
    
    warning: no previously-included files matching '*.dll' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching 'coverage.xml' found anywhere in distribution
    warning: no previously-included files matching 'appveyor.yml' found anywhere in distribution
    no previously-included directories found matching 'docs/_build'
Downloading/unpacking foolscap>=0.12.6 (from tahoe-lafs==1.12.1.post9)
  Downloading foolscap-0.12.6-py2-none-any.whl (309kB): 309kB downloaded
Downloading/unpacking pycrypto>=2.1.0,!=2.2,!=2.4 (from tahoe-lafs==1.12.1.post9)
  Downloading pycrypto-2.6.1.tar.gz (446kB): 446kB downloaded
  Running setup.py (path:/tmp/pip-build-mX00xZ/pycrypto/setup.py) egg_info for package pycrypto
    
Downloading/unpacking pycryptopp>=0.6.0 (from tahoe-lafs==1.12.1.post9)
  Downloading pycryptopp-0.7.1.869544967005693312591928092448767568728501330214.tar.gz (2.0MB): 2.0MB downloaded
  Running setup.py (path:/tmp/pip-build-mX00xZ/pycryptopp/setup.py) egg_info for package pycryptopp
    
Downloading/unpacking service-identity (from tahoe-lafs==1.12.1.post9)
  Downloading service_identity-16.0.0-py2.py3-none-any.whl
Downloading/unpacking characteristic>=14.0.0 (from tahoe-lafs==1.12.1.post9)
  Downloading characteristic-14.3.0-py2.py3-none-any.whl
Downloading/unpacking pyasn1>=0.1.8 (from tahoe-lafs==1.12.1.post9)
  Downloading pyasn1-0.2.3-py2.py3-none-any.whl (53kB): 53kB downloaded
Downloading/unpacking pyasn1-modules>=0.0.5 (from tahoe-lafs==1.12.1.post9)
  Downloading pyasn1_modules-0.0.8-py2.py3-none-any.whl
Downloading/unpacking Twisted[tls]>=16.1.0 (from tahoe-lafs==1.12.1.post9)
  Downloading Twisted-17.1.0.tar.bz2 (3.0MB): 3.0MB downloaded
  Running setup.py (path:/tmp/pip-build-mX00xZ/Twisted/setup.py) egg_info for package Twisted
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'tests'
    warning: no previously-included files found matching 'examplesetup.py'
    no previously-included directories found matching 'src/exampleproj'
    no previously-included directories found matching 'src/incremental/newsfragments'
    
    Installed /tmp/pip-build-mX00xZ/Twisted/incremental-16.10.1-py2.7.egg
    
    warning: no previously-included files matching '*.misc' found under directory 'src/twisted'
    warning: no previously-included files matching '*.bugfix' found under directory 'src/twisted'
    warning: no previously-included files matching '*.doc' found under directory 'src/twisted'
    warning: no previously-included files matching '*.feature' found under directory 'src/twisted'
    warning: no previously-included files matching '*.removal' found under directory 'src/twisted'
    warning: no previously-included files matching 'NEWS' found under directory 'src/twisted'
    warning: no previously-included files matching 'README' found under directory 'src/twisted'
    warning: no previously-included files matching 'topfiles' found under directory 'src/twisted'
    warning: no previously-included files found matching 'src/twisted/topfiles/CREDITS'
    warning: no previously-included files found matching 'src/twisted/topfiles/ChangeLog.Old'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files found matching 'appveyor.yml'
    no previously-included directories found matching 'bin'
    no previously-included directories found matching 'admin'
    no previously-included directories found matching '.travis'
    warning: no previously-included files found matching 'docs/historic/2003'
    warning: no previously-included files matching '*' found under directory 'docs/historic/2003'
  Installing extra requirements: u'tls'
Downloading/unpacking Nevow>=0.11.1 (from tahoe-lafs==1.12.1.post9)
  Downloading Nevow-0.14.2-py2-none-any.whl (447kB): 447kB downloaded
Downloading/unpacking pyOpenSSL>=0.14 (from tahoe-lafs==1.12.1.post9)
  Downloading pyOpenSSL-16.2.0-py2.py3-none-any.whl (43kB): 43kB downloaded
Downloading/unpacking PyYAML>=3.11 (from tahoe-lafs==1.12.1.post9)
  Downloading PyYAML-3.12.tar.gz (253kB): 253kB downloaded
  Running setup.py (path:/tmp/pip-build-mX00xZ/PyYAML/setup.py) egg_info for package PyYAML
    
Downloading/unpacking six>=1.10.0 (from tahoe-lafs==1.12.1.post9)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking appdirs>=1.4.0 (from setuptools>=11.3->tahoe-lafs==1.12.1.post9)
  Downloading appdirs-1.4.3-py2.py3-none-any.whl
Downloading/unpacking packaging>=16.8 (from setuptools>=11.3->tahoe-lafs==1.12.1.post9)
  Downloading packaging-16.8-py2.py3-none-any.whl
Downloading/unpacking pyutil>=1.3.19 (from zfec>=1.1.0->tahoe-lafs==1.12.1.post9)
  Downloading pyutil-2.0.0.tar.gz (125kB): 125kB downloaded
  Running setup.py (path:/tmp/pip-build-mX00xZ/pyutil/setup.py) egg_info for package pyutil
    
Downloading/unpacking attrs (from service-identity->tahoe-lafs==1.12.1.post9)
  Downloading attrs-16.3.0-py2.py3-none-any.whl
Downloading/unpacking constantly>=15.1 (from Twisted[tls]>=16.1.0->tahoe-lafs==1.12.1.post9)
  Downloading constantly-15.1.0-py2.py3-none-any.whl
Downloading/unpacking incremental>=16.10.1 (from Twisted[tls]>=16.1.0->tahoe-lafs==1.12.1.post9)
  Downloading incremental-16.10.1-py2.py3-none-any.whl
Downloading/unpacking Automat>=0.3.0 (from Twisted[tls]>=16.1.0->tahoe-lafs==1.12.1.post9)
  Downloading Automat-0.5.0-py2.py3-none-any.whl
Downloading/unpacking idna>=0.6 (from Twisted[tls]>=16.1.0->tahoe-lafs==1.12.1.post9)
  Downloading idna-2.5-py2.py3-none-any.whl (55kB): 55kB downloaded
Downloading/unpacking cryptography>=1.3.4 (from pyOpenSSL>=0.14->tahoe-lafs==1.12.1.post9)
  Downloading cryptography-1.8.1.tar.gz (423kB): 423kB downloaded
  Running setup.py (path:/tmp/pip-build-mX00xZ/cryptography/setup.py) egg_info for package cryptography
    
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
Downloading/unpacking pyparsing (from packaging>=16.8->setuptools>=11.3->tahoe-lafs==1.12.1.post9)
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB): 56kB downloaded
Downloading/unpacking zbase32>=1.0 (from pyutil>=1.3.19->zfec>=1.1.0->tahoe-lafs==1.12.1.post9)
  Downloading zbase32-1.1.5.tar.gz
  Running setup.py (path:/tmp/pip-build-mX00xZ/zbase32/setup.py) egg_info for package zbase32
    
Downloading/unpacking asn1crypto>=0.21.0 (from cryptography>=1.3.4->pyOpenSSL>=0.14->tahoe-lafs==1.12.1.post9)
  Downloading asn1crypto-0.22.0-py2.py3-none-any.whl (97kB): 97kB downloaded
Downloading/unpacking enum34 (from cryptography>=1.3.4->pyOpenSSL>=0.14->tahoe-lafs==1.12.1.post9)
  Downloading enum34-1.1.6-py2-none-any.whl
Downloading/unpacking ipaddress (from cryptography>=1.3.4->pyOpenSSL>=0.14->tahoe-lafs==1.12.1.post9)
  Downloading ipaddress-1.0.18-py2-none-any.whl
Downloading/unpacking cffi>=1.4.1 (from cryptography>=1.3.4->pyOpenSSL>=0.14->tahoe-lafs==1.12.1.post9)
  Downloading cffi-1.10.0.tar.gz (418kB): 418kB downloaded
  Running setup.py (path:/tmp/pip-build-mX00xZ/cffi/setup.py) egg_info for package cffi
    
Downloading/unpacking pycparser (from cffi>=1.4.1->cryptography>=1.3.4->pyOpenSSL>=0.14->tahoe-lafs==1.12.1.post9)
  Downloading pycparser-2.17.tar.gz (231kB): 231kB downloaded
  Running setup.py (path:/tmp/pip-build-mX00xZ/pycparser/setup.py) egg_info for package pycparser
    
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
Installing collected packages: setuptools, zfec, zope.interface, foolscap, pycrypto, pycryptopp, service-identity, characteristic, pyasn1, pyasn1-modules, Twisted, Nevow, pyOpenSSL, PyYAML, six, tahoe-lafs, appdirs, packaging, pyutil, attrs, constantly, incremental, Automat, idna, cryptography, pyparsing, zbase32, asn1crypto, enum34, ipaddress, cffi, pycparser
  Found existing installation: setuptools 5.5.1
    Uninstalling setuptools:
      Successfully uninstalled setuptools
  Running setup.py install for zfec
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/foo/code/tahoe-lafs/venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 10, in <module>
        from six.moves import filter, map
    ImportError: No module named six.moves
    Complete output from command /home/foo/code/tahoe-lafs/venv/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-mX00xZ/zfec/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tAdJ6k-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/foo/code/tahoe-lafs/venv/include/site/python2.7:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/foo/code/tahoe-lafs/venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 10, in <module>

    from six.moves import filter, map

ImportError: No module named six.moves

----------------------------------------
Cleaning up...
Command /home/foo/code/tahoe-lafs/venv/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-mX00xZ/zfec/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tAdJ6k-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/foo/code/tahoe-lafs/venv/include/site/python2.7 failed with error code 1 in /tmp/pip-build-mX00xZ/zfec
Storing debug log for failure in /home/user/.pip/pip.log
```

**Comment by warner** [comment]
Thanks for the detailed logfile.. I see that your box is starting from setuptools 5.5.1, which is pretty old. I'm guessing that's coming from your virtualenv. I'll try installing that older version and see if I can reproduce it. (everything works normally on my box that has virtualenv-15.1.0, which installs setuptools-34.4.1).

I suppose maybe what we need is to declare a minimum version of virtualenv in the docs, with instructions to install those extra packages as a workaround if you don't have that. I suspect the real problem is that the older setuptools is not spotting the fact that the new version of setuptools requires six and appdirs, but I need to experiment to find out for sure.

**Comment by tpltnt** [comment]
Hmmm ...
Upgrading setuptools does not seem to have any effect.
```
(venv)testmachine% pip install --upgrade setuptools
Requirement already up-to-date: setuptools in ./venv/lib/python2.7/site-packages
Requirement already up-to-date: packaging>=16.8 in ./venv/lib/python2.7/site-packages (from setuptools)
Requirement already up-to-date: appdirs>=1.4.0 in ./venv/lib/python2.7/site-packages (from setuptools)
Requirement already up-to-date: six>=1.6.0 in ./venv/lib/python2.7/site-packages (from setuptools)
Requirement already up-to-date: pyparsing in ./venv/lib/python2.7/site-packages (from packaging>=16.8->setuptools)
```
I will look into using a more up to date virtualenv.

**Comment by warner** [comment]
Cool. What version of virtualenv did you have? (and what version of Debian did it come from)?

**Comment by tpltnt** [comment]
The testbox has virtualenv version 1.11.6, which is the default on Debian 8.7.

**Comment by meejah** [comment]
I'm merging this because it's an improvement.

However, we still should: 

 - document our minimum setuptools version
 - probably include "pip install --upgrade pip" in there too (I'm not sure if that's *necessary*, but I always do that on new virtualenvs on Debian boxes).

**Comment by meejah** [comment]
Thanks for the PR, @tpltnt

**Pull request merged**
