### PR TITLE
Added a white stroke to the Tahoe logo

### PR DESCRIPTION
**Pull request by AnXh3L0**
This makes the logo visible when the dark/dimmed GitHub theme is being used. Related to Trac ticket 3677 https://tahoe-lafs.org/trac/tahoe-lafs/ticket/3677

### CODE REVIEW

**Comment by AnXh3L0** [comment]
github-dark-theme
github-dimmed-theme

Previews as in the files attached above.

**Comment by sajith** [comment]
Welcome @AnXh3L0, and thank you!

This PR needs a newsfragment file, so that the "lint" check will pass.  I think the file can be either `newsfragments/3677.minor` (which can be empty) or `newsfragments/3677.documentation` (which should contain a short summary of the change).  Those newsfragment files are used to update the NEWS file by [towncrier](https://pypi.org/project/towncrier/).

(This should be documented a little more prominently, but it is not...)

**Comment by May-Lee** [comment]
> Welcome @AnXh3L0, and thank you!
> 
> This PR needs a newsfragment file, so that the "lint" check will pass. I think the file can be either `newsfragments/3677.minor` (which can be empty) or `newsfragments/3677.documentation` (which should contain a short summary of the change). Those newsfragment files are used to update the NEWS file by [towncrier](https://pypi.org/project/towncrier/).
> 
> (This should be documented a little more prominently, but it is not...)

ah, I should have pointed @AnXh3L0 to https://github.com/tahoe-lafs/tahoe-lafs/blob/master/CONTRIBUTORS.rst. I will add that to the onboarding checklist!

**Comment by AnXh3L0** [comment]
Thanks for the comments @sajith, opened a new PR #1070 for it, closing this one.

**Comment by sajith** [comment]
That did not have to be a new PR?  But okay, whatever that works for you. :-)

**Pull request closed without merging**
