### PR TITLE
4131: Remove Python 3.8 EOL and unit test on Python 3.9 instead

### PR DESCRIPTION
**Pull request by btlogy**
Removing all references to Python 3.8 and bumping 3.9 on `oraclelinux-8` builder.
This should fix both [ticket:4131](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/4131) and [ticket:4135](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/4135).

**WARN**: this change will require to publish a new image for `tahoelafsci/oraclelinux:8-py3.9` in Docker Hub (should be covered by [ticket:4143](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/4143) and #1409 : WiP).

### CODE REVIEW

**Comment by btlogy** [comment]
This PR does not show the checks from CircleCI, likely becasue the branch had already triggered a build here:

https://app.circleci.com/pipelines/github/LeastAuthority/tahoe-lafs?branch=4131.remove-python-3.8-only

But the `oraclelinux-8` build will not start properly until we build and publish a new docker image.

@meejah: do you know how do to this?

**Comment by sajith** [comment]
@btlogy There's a hint here:

https://github.com/tahoe-lafs/tahoe-lafs/blob/e24b9ec0e876a901d943b75c9a38f829d3d9ae73/.circleci/config.yml#L57-L68

I do not mean to say that this is something I have done myself though. :-)

**Comment by btlogy** [comment]
Thank you @sajith

I've seen this block before, but I was assuming only project/org admin could trigger builds with parameters...

Even if I was apparently wrong (maybe any org-member can trigger?): the way CircleCI works with PR from forks seems to allow me to trigger the build on this branch `4131.remove-python-3.8-only` only from the LeastAuthority org./repo., which has no access to the required DockerHub secret owned by the targeted Tahoe-LAFS org./repo.  :-/.

On top of this, CircleCI is throwing me a weird message when I try that parametrized build:

> Job was rejected because this version of Docker is not supported on this resource class. Try removing the version of Docker in your .circleci/config.yml and re-running

I'll try a new PR from my own fork, this one may be trigger-able from Tahoe-LAFS org...

**Comment by btlogy** [comment]
I've PR only the bump of Python version in #1407 and while I can finally see the branch to be triggered (`pull/1407`), I'm not allowed to do so:

> Permission denied.

As mentioned in this [comment](https://github.com/tahoe-lafs/tahoe-lafs/pull/1407#issuecomment-2529033102): only a GH admin can do this.

**Comment by sajith** [comment]
The error I see on `ci:circleci: build-image-debian-11` etc is "Job was rejected because this version of Docker is not supported on this resource class. Try removing the version of Docker in your .circleci/config.yml and re-running"

What does that mean? Where is this "version of Docker in your .circleci/config.yml" that they speak of?

**Comment by meejah** [comment]
> @meejah: do you know how do to this?

No, I do not.

**Comment by btlogy** [comment]
> @btlogy I need to ask the dumb question now. Will the image build workflow succeed if you push to this repository, instead of LeastAuthority fork or btlogy fork?

Yes and no, I guess :-) Maybe (as discussed in the N&B), if my pushed branch is also turning the `build-images` to `true` by default...
But if I could push directly into Tahoe-LAFS repo, I might have the sufficient permissions to manually trigger the build with the same parameter.

> The error I see on `ci:circleci: build-image-debian-11` etc is "Job was rejected because this version of Docker is not supported on this resource class. Try removing the version of Docker in your .circleci/config.yml and re-running"
> 
> What does that mean? Where is this "version of Docker in your .circleci/config.yml" that they speak of?

No idea really. It's the same config file, so it did not made much sense to me back then.
If I remember correctly, I've tried from my own fork, and it does not show this senseless error.

**Comment by btlogy** [comment]
@sajith We've just bumped into this weird error with @meejah and now I think I get the meaning (just had to search a bit):

https://discuss.circleci.com/t/remote-docker-image-deprecations-and-eol-for-2024/50176

We can no longer pin the version of docker as we previously did here:

https://github.com/tahoe-lafs/tahoe-lafs/blob/dc6ea19d9697a4e95cf8cad999205ec7d0ac6843/.circleci/config.yml#L615-L616

Hopefully, my last commit on #1409 will avoid this error...

**Comment by btlogy** [comment]
The above Docker error has been dealt with: see this [comment](https://github.com/tahoe-lafs/tahoe-lafs/pull/1409#issuecomment-2535335768).

Cc: @sajith

**Comment by btlogy** [comment]
From my previous investigations in #1405:

There are still 2 places I'm not sure we need to change anything in regards with Python 3.8 (out of my league):

- https://github.com/tahoe-lafs/tahoe-lafs/blob/e24b9ec0e876a901d943b75c9a38f829d3d9ae73/src/allmydata/storage/http_client.py#L1104-L1108
- https://github.com/tahoe-lafs/tahoe-lafs/blob/e24b9ec0e876a901d943b75c9a38f829d3d9ae73/nix/service-identity.nix#L22

Any idea (about the first at least) @meejah?

**Comment by btlogy** [comment]
This PR is now pending on #1409 because it re-activates the `oraclelinux-8` builder which is defined in that branch (5ec03c66) and is not yet in the master.

**Comment by btlogy** [comment]
This PR should not be merged before #1409: sorry, it should have stayed as a draft.

In addition, there are still 2 items to review before putting it back as ready (see this [comment](https://github.com/tahoe-lafs/tahoe-lafs/pull/1406#issuecomment-2538529203)).

**Comment by btlogy** [comment]
> In addition, there are still 2 items to review before putting it back as ready (see this [comment](https://github.com/tahoe-lafs/tahoe-lafs/pull/1406#issuecomment-2538529203)).

- [x] I'll assume that `Python 3.8 that will error out` can be read as `Python >= 3.8 that will error out`,
- [x] and my concern about [`pythonOlder "3.8"`](https://github.com/tahoe-lafs/tahoe-lafs/blob/e24b9ec0e876a901d943b75c9a38f829d3d9ae73/nix/service-identity.nix#L22) is no longer the master (since #1403).

Then we are just pending on #1409

**Comment by meejah** [comment]
This (or, approximately this) is now merged as part of #1409 / #1418 as far as I know. Please re-open if that's not true.

**Comment by btlogy** [comment]
> This (or, approximately this) is now merged as part of #1409 / #1418 as far as I know. Please re-open if that's not true.

#1418 has not brought back `oraclelinux-8` with Python 3.9 like this PR was proposing.

**Comment by meejah** [comment]
I guess I'll assume that the last comment means to re-open. Please close if that wasn't the intention. I assumed you're able to re-open this, but maybe not.

**Pull request closed without merging**
