### PR TITLE
2416.allow twisted 13 on windows.1

### PR DESCRIPTION
**Pull request by daira**
fixes ticket:2416 and ticket:2415

### CODE REVIEW

**Comment by daira** [comment]
Please hold off merging this; it's not behaving as I expected (possibly because Twisted is a setup dependency).

**Comment by daira** [comment]
There were two problems preventing this from working:
* The first, which is fixed by the last two commits above, was that the `setup_requires` hack for Nevow was interfering with the ability to build a newer Twisted when an older one was already installed.
* The second was that I now need to build Twisted >= 13.0.0 eggs for 32-bit and 64-bit Windows.

**Comment by warner** [comment]
NEWS changes look accurate to me. Thanks for simplifying that. I look forward to the day when we get rid of the platform switch (and then get rid of `_auto_deps.py` too).

**Comment by warner** [comment]
The rest of the changes make sense to me, and seem to work correctly on a unix VM. +1. Might want to rebase to current master before merging, I've landed the other two PRs since this one forked off.

**Comment by warner** [comment]
landed already

**Pull request closed without merging**
