### PR TITLE
New style classes

### PR DESCRIPTION
**Pull request by tpltnt**
Hi there,

as part of the effort to port Tahoe-LAFS to Python 3 I transformed all old-style classes into new-style ones.

Cheers,
tpltnt

---
This change is [Reviewable](https://reviewable.io/reviews/tahoe-lafs/tahoe-lafs/613)

### CODE REVIEW

**Comment by tpltnt** [comment]
I don't see any (easy) was to detect old-style classes except grepping and a (large) blacklist for false positives.

**Comment by exarkun** [comment]
> I don't see any (easy) was to detect old-style classes except grepping and a (large) blacklist for false positives.

I imagine something like this (untested):

```
from twisted.python.modules import getModule

for mod in getModule("allmydata").walkModules():
    for attr in mod.iterAttributes():
        value = attr.load()
        if issubclass(value, types.ClassType):
            print(attr.name)
```

possibly with some error handling to deal with modules that aren't importable on all platforms.

**Comment by tpltnt** [comment]
Regression test is added.

**Comment by meejah** [comment]
great, thanks :)

**Comment by exarkun** [comment]
This seems to have missed at least a few classes and it seems like the test that was added isn't quite right.

**Pull request merged**
