### PR TITLE
delete invalid pidfile on node startup

### PR DESCRIPTION
**Pull request by lpirl**
This is a follow-up to #440 .
Please understand this as a proposal – I have no clue if this patch complies with your coding conventions and style :)

### CODE REVIEW

**Comment by lpirl** [comment]
To test the error message – which is supposed to be printed when an invalid PID file exists upon node startup – all I could come up with was to actually create and start a node. It feels a bit overkill. RFC (also, again, because I am not familiar with the project's coding style).

**Comment by meejah** [comment]
Hi @lpirl yeah the reason some of these CLI things don't have tests is "because hard", I think.

The strategy I see some of them taking is exactly that: create some fake-stuff that looks like a node-dir and then start it (often faking out some other things so avoid "real" startup). You can call `allmydata.scripts.runner.dispatch` with a config and fakes for stdio things (which is what some of the other tests do). Calling start/stop directly as you've done seems fine to me too.

That said, this is of course not ideal. There's also a bunch of CLI dispatch things that are ... "not great". Given that this area *didn't* have any coverage at all before your patch, "whatever works" is fine for some tests. Also, though, if you see a better way to do things feel free to refactor a bit! :)

**Comment by lpirl** [comment]
Alright, thanks @meejah. Also for encouraging to refactor (well, I won't refactor for the sake of it, but in case I contribute again and things jump at me along the way, I can try).

**Comment by lpirl** [comment]
Are there any experiences which would explain why AppVeyor gets stuck with the test that starts a node?

**Comment by meejah** [comment]
See https://github.com/tahoe-lafs/tahoe-lafs/pull/450

**Pull request closed without merging**
