### PR TITLE
4141: Pin the base versions of the builders to improve reproducibility while checking PRs

### PR DESCRIPTION
**Pull request by btlogy**
Cherry-picked from #1395

### CODE REVIEW

**Comment by btlogy** [comment]
@meejah: I'm not sure why, but even the Nix jobs have succeeded tonight (may Santa :gift: - his early clone is around in BE and NL those days)!

**Comment by btlogy** [comment]
I was missing the new fragment (though that check was not reported as failed here!).

**Comment by meejah** [comment]
"test_system" is the "often flaky one".

**Comment by btlogy** [comment]
> "test_system" is the "often flaky one".

We see other one a lot too:
```
test_verify_one_bad_encprivkey
Classname:allmydata.test.mutable.test_checker.Checker
```

More about this in ticket [4126](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/4126)

**Comment by meejah** [comment]
The sometimes failures of `test_verify_one_bad_encprivkey` seem to at least have a chance of being a real bug...

**Pull request merged**
