### PR TITLE
Add documentation on OpenMetrics statistics endpoint.

### PR DESCRIPTION
**Pull request by hacklschorsch**
In #1125 @exarkun and I added an OpenMetrics format statistics exporter.
This PR adds the documentation we forgot to write.

references ticket:3786

### CODE REVIEW

**Comment by hacklschorsch** [comment]
I uploaded the [dashboard to Grafana.com](https://grafana.com/grafana/dashboards/16894-tahoe-lafs/) only minutes before issuing the PR.
Currently the link to it still me a 404; the [dashboard search engine](https://grafana.com/grafana/dashboards/) on grafana.com already finds my entry.
Thus I would expect the 404 to soon be fixed.

**Comment by meejah** [comment]
Hmm, still 404's for me ..

**Comment by hacklschorsch** [comment]
Now it's online. Cache invalidation sure is hard.

**Comment by hacklschorsch** [comment]
What is it with that failing windows build? Is that intermittent?

> x CI / coverage (windows-latest, 3.9) (pull_request)

**Comment by meejah** [comment]
i asked it to re-run :crossed_fingers:

**Review by meejah — APPROVED** [review]

**Pull request merged**
