### PR TITLE
Unbreak macOS GitHub actions

### PR DESCRIPTION
**Pull request by itamarst**
Fixes https://tahoe-lafs.org/trac/tahoe-lafs/ticket/3810

### CODE REVIEW

**Comment by itamarst** [comment]
Uh... I don't think this can be merged. The macos-10.15 builders are ... not available? So possibly GitHub Actions just decommissioned them altogether.

**Comment by exarkun** [comment]
Do we need to get Python 2.7 installed onto macos-latest then?  Or should we move our macOS CI to ... GitLab?

**Comment by itamarst** [comment]
How about dropping Python 2.7 macOS support? :grinning:

**Comment by itamarst** [comment]
I was going to retry and see if macOS VMs are back but GitHub Actions is having a bad day... https://www.githubstatus.com/

**Comment by itamarst** [comment]
Looks like 10.15 builders are back, maybe? In which case I can merge this.

**Comment by itamarst** [comment]
Issue is nothing to do with builders at this point, just GitHub's branch protection settings have the wrong checks enabled since the names changed. Someone with access to repo Settings can fix this.

**Comment by exarkun** [comment]
> Issue is nothing to do with builders at this point, just GitHub's branch protection settings have the wrong checks enabled since the names changed. Someone with access to repo Settings can fix this.

Yep, makes sense to me.  I went to the GitHub settings page and removed the three "macos-latest" checks and added three similar "macos-10.15" checks.

**Pull request merged**
