### PR TITLE
Fix MIME parsing bug

### PR DESCRIPTION
**Pull request by itamarst**
Fixes https://tahoe-lafs.org/trac/tahoe-lafs/ticket/3854

Unclear to me if there's better way to extract content-type (there probably is?) than adhoc parser.

### CODE REVIEW

**Comment by itamarst** [comment]
The SFTP integration test failures seem unrelated (they pass locally for me), probably some new package release.

**Review by meejah — APPROVED** [review]
LGTM
(I didn't look into the integration failures on this branch, but saw them on one of mine..)

**Comment by itamarst** [comment]
Hm. Actually a little worried about the ad-hoc parser now...

**Comment by itamarst** [comment]
But reading and checking it again, seems fine.

**Pull request merged**
