### PR TITLE
update to python3-compatible foolscap

### PR DESCRIPTION
**Pull request by meejah**
This change is [Reviewable](https://reviewable.io/reviews/tahoe-lafs/tahoe-lafs/700)

### CODE REVIEW

**Comment by exarkun** [comment]
I guess the motivation for this change is that it is a necessary step in the Python 3 porting process?

**Comment by meejah** [comment]
Yes -- and to make sure that it works with current CI etc (because we need a release against a version of foolscap that supports both 2 and 3).

**Comment by meejah** [comment]
(I just rebased this).

**Comment by sajith** [comment]
Looks like foolscap on NixOS is at version [0.13.1](https://github.com/NixOS/nixpkgs-channels/blob/nixos-19.09-small/pkgs/development/python-modules/foolscap/default.nix), which explains [this CI failure](https://app.circleci.com/pipelines/github/tahoe-lafs/tahoe-lafs/114/workflows/758bc11d-31b4-4eba-9b5f-a7d8f844123a/jobs/19427/steps).

I am not sure what caused [the other failure](https://app.circleci.com/pipelines/github/tahoe-lafs/tahoe-lafs/114/workflows/758bc11d-31b4-4eba-9b5f-a7d8f844123a/jobs/19422/steps) though.   That probably must be a transient error?

**Comment by exarkun** [comment]
> Looks like foolscap on NixOS is at version 0.13.1, which explains this CI failure.

Yes.  Perhaps we should not require exactly 20.4.0 but instead >=0.13.1?  We *could* upgrade Foolscap on the NixOS builder and I'm happy to help with that but I wonder if we really want to have the hard requirement on 20.4.0 right now.

> I am not sure what caused the other failure though. That probably must be a transient error?

Yea, uh, weird.  From the build log:

```
  deprecations: commands succeeded
  upcoming-deprecations: commands succeeded
  congratulations :)
+ '[' -n /tmp/artifacts ']'
++ dirname /tmp/artifacts/junit/unittests/results.xml
+ mkdir -p /tmp/artifacts/junit/unittests
+ /tmp/venv/bin/subunit2junitxml
+ false
 ```

So the jobs themselves succeeded.  Then `subunit2junitxml` failed but we don't get to see any details about why.  I guess we could try that job again and see what happens.  If it is a transient error then it's not one I'm familiar with.

**Comment by sajith** [comment]
With NixOS, I am not sure about the right way to go about.  Perhaps upgrading foolscap is the right thing, since that is the goal of this PR, and since that is we eventually need to do anyway.  This way we could also catch any potential issues with the new foolscap early enough?

I think that the deprecactions failure is misleading.  I just noticed that there are more hints about failures under the "tests" tab: they are all `allmydata.test.test_connections.I2P` failures, with error messages like `ImportError: No module named i2p`.  That makes more sense.

**Comment by exarkun** [comment]
> With NixOS, I am not sure about the right way to go about. Perhaps upgrading foolscap is the right thing, since that is the goal of this PR, and since that is we eventually need to do anyway. This way we could also catch any potential issues with the new foolscap early enough?
> 
> I think that the deprecactions failure is misleading. I just noticed that there are more hints about failures under the "tests" tab: they are all `allmydata.test.test_connections.I2P` failures, with error messages like `ImportError: No module named i2p`. That makes more sense.

I did think that the new Foolscap dropped supported for I2P but I think Brian disagreed with me at some point.  Not sure what is really going on there.  If that's really the case I wonder why it would be green elsewhere.

**Comment by sajith** [comment]
It is that txi2p haven't had a release that supports Python 3.  (I think txi2p's master branch has Python 3 support, so this probably is not a permanent situation.)  Which led to foolscap [dropping i2p](https://github.com/warner/foolscap/commit/2a4501eec73e3d771894fabb1301081460cb40b5#diff-2eeaed663bd0d25b7e608891384b7298), which led to us getting these errors.

Can the test suite do feature detection?  Is it even a good idea?

**Comment by exarkun** [comment]
> It is that txi2p haven't had a release that supports Python 3. (I think txi2p's master branch has Python 3 support, so this probably is not a permanent situation.) Which led to foolscap dropping i2p, which led to us getting these errors.

Still ... why is it green on the other jobs?

**Comment by sajith** [comment]
That seems like an interesting mystery to me.  Foolscap 20.4.0 certainly removed `connections.i2p`... so I don't know what is going on there.  Caching, maybe?

**Comment by exarkun** [comment]
Hm.  Could be.  But a cursory look at one of the passing builds shows that it is using foolscap 20.4.0:

> py27-coverage installed: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.,-f file:///tmp/wheelhouse,appdirs==1.4.3,atomicwrites==1.4.0,attrs==19.3.0,autobahn==19.11.2,Automat==20.2.0,backports.functools-lru-cache==1.6.1,bcrypt==3.1.7,beautifulsoup4==4.9.0,boltons==20.1.0,certifi==2020.4.5.1,cffi==1.14.0,chardet==3.0.4,click==7.1.2,configparser==4.0.2,constantly==15.1.0,contextlib2==0.6.0.post1,coverage==4.5.4,cryptography==2.9.2,decorator==4.4.2,distlib==0.3.0,eliot==1.7.0,enum34==1.1.10,extras==1.0.0,filelock==3.0.12,fixtures==3.0.0,**foolscap==20.4.0**,funcsigs==1.0.2,greenlet==0.4.15,hkdf==0.0.3,html5lib==1.0.1,humanize==1.0.0,hyperlink==19.0.0,hypothesis==4.57.1,idna==2.9,importlib-metadata==1.6.0,importlib-resources==1.5.0,incremental==17.5.0,ipaddress==1.0.23,Jinja2==2.11.2,linecache2==1.0.0,magic-wormhole==0.12.0,MarkupSafe==1.1.1,mock==3.0.5,more-itertools==5.0.0,Nevow==0.14.5,packaging==20.3,Parsley==1.3,pathlib2==2.3.5,pbr==5.4.5,pluggy==0.13.1,py==1.8.1,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycparser==2.20,pyflakes==2.1.0,PyHamcrest==1.10.1,PyNaCl==1.3.0,pyOpenSSL==19.1.0,pyparsing==2.4.7,pyrsistent==0.16.0,pytest==4.6.9,pytest-twisted==1.12,python-mimeparse==1.6.0,python-subunit==1.4.0,pyutil==3.3.0,PyYAML==5.3.1,requests==2.23.0,scandir==1.10.0,service-identity==18.1.0,singledispatch==3.4.0.3,six==1.14.0,sortedcontainers==2.1.0,soupsieve==1.9.5,spake2==0.8,subunitreporter==19.3.2,tahoe-lafs==1.14.0.post236,testtools==2.4.0,toml==0.10.0,towncrier==19.2.0,tox==3.15.0,tqdm==4.46.0,traceback2==1.4.0,treq==20.4.1,Twisted==20.3.0,txaio==18.8.1,txi2p==0.3.2,txtorcon==20.0.0,typing==3.7.4.1,unittest2==1.1.0,urllib3==1.25.9,virtualenv==20.0.20,wcwidth==0.1.9,webencodings==0.5.1,zfec==1.5.3,zipp==1.2.0,zope.interface==5.1.0

**Comment by sajith** [comment]
I just re-ran debian-9 on CircleCI, with ssh enabled.  This file exists, but I believe it should not:

`/tmp/tahoe-lafs.tox/py27-coverage/lib/python2.7/site-packages/foolscap/connections/i2p.py`

Also:

```
nobody@3d1fc1e8210d:/tmp$ cat /tmp/tahoe-lafs.tox/py27-coverage/lib/python2.7/site-packages/foolscap/_version.py

# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-04-12T16:30:53-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "845bea550447991b194ef884713a7b3be4b4a6c2",
 "version": "20.4.0"
}
'''  # END VERSION_JSON
```

**Comment by sajith** [comment]
I ran this command, which is what happens in CircleCI setup step:

```
/tmp/venv/bin/tox -r -v -c /tmp/project/tox.ini --workdir /tmp/tahoe-lafs.tox --notest -e py27-coverage
```

Per logs:
```
nobody@3d1fc1e8210d:/tmp$ cat /tmp/tahoe-lafs.tox/py27-coverage/log/py27-coverage-2.log
...
Collecting foolscap==20.4.0 (from tahoe-lafs==1.14.0.post236)
  Using cached https://files.pythonhosted.org/packages/82/f8/be775e689bd579b102a9b7aa731fac8726e27f97a2659481098488e3eac3/foolscap-20.4.0-py2.py3-none-any.whl
...
```
Seems that the `.whl` file that got uploaded to pypi has `connections/i2p.py` (I downloaded it locally, and looked at its contents, just to make sure that I am not really hallucinating), whereas the corresponding source package does not.  I don't know how this could have happened.  I guess this should be an issue against foolscap.

On the other hand, the `upcoming-deprecations` environment does this:

```
nobody@186ccf1158fd:~$ less /tmp/tahoe-lafs.tox/upcoming-deprecations/log/upcoming-deprecations-1.log
...
Looking in links: file:///tmp/wheelhouse
Collecting git+https://github.com/warner/foolscap
  Cloning https://github.com/warner/foolscap to /tmp/pip-req-build-joNSSC
  Running command git clone -q https://github.com/warner/foolscap /tmp/pip-req-build-joNSSC
...
Building wheels for collected packages: foolscap
  Building wheel for foolscap (setup.py): started
  Building wheel for foolscap (setup.py): finished with status 'done'
  Created wheel for foolscap: filename=foolscap-20.4.0-py2.py3-none-any.whl size=312122 sha256=410e81ac960fec34b8dfae7b6b4c94ed7fe9ef21c7b232b558f9011a0e24f32b
  Stored in directory: /tmp/pip-ephem-wheel-cache-KrtE7b/wheels/2d/79/75/c9075f527089527009ddd571e6145a6fedc9ab873ecb8edea0
Successfully built foolscap
...
```
Also, `deprecations` environment uses the pypi package.

**Review by exarkun — COMMENTED** [review]
I wonder if the times have overtaken this one?  in master@HEAD we now have conditional foolscap dependencies with 20.4.0 or newer required on Python 3.

Maybe that's sufficient until such time as we drop Python 2 support?

**Pull request closed without merging**
