### PR TITLE
Port stats to Python 3

### PR DESCRIPTION
**Pull request by chadwhitacre**

### CODE REVIEW

**Comment by chadwhitacre** [comment]
Rebased on latest master (ulterior motive: bump stuck CI).

**Comment by exarkun** [comment]
Hackishly trying to tickle CircleCI into doing its job.

**Comment by itamarst** [comment]
So the decision here is that stats are all unicode keyed, which makes sense. Probably that is assumed in already ported code, we'll see.

**Review by itamarst — APPROVED** [review]
Thank you!

**Pull request merged**
