### PR TITLE
1432.watchdog magic folder

### PR DESCRIPTION
**Pull request by crwood**
This PR leverages the [watchdog](https://pypi.org/project/watchdog/) library to provide fallback filesystem-monitoring capabilities (via `FSEvents` or `kqueue`) on platforms that lack `inotify` (Linux) and/or `ReadDirectoryChangesW` (Windows), thereby enabling "magic-folder" functionality on macOS and various BSD-flavors ([ticket 1432](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/1432)). See also PR #401 (which this supersedes).

The vast majority of this code was written by @david415, who should largely be credited for this work -- though thanks are due also to @vu3rdd, who more recently brought the code back to life and into a mergeable state. I merely provided some small cleanups and tweaks to ensure harmony with PRs #388 and #482 and fixed a minor bug that I spotted along the way. :)

---
This change is [Reviewable](https://reviewable.io/reviews/tahoe-lafs/tahoe-lafs/516)

### CODE REVIEW

**Comment by crwood** [comment]
The only test-failure is caused by [this](https://github.com/crwood/tahoe-lafs/blob/bc65dbd637d61aabfd6d433279d6bed80f5aaaa3/src/allmydata/test/test_magic_folder.py#L1000) deferred not firing on Travis for some reason. I am unable to reproduce the failure locally on a MacBook Air, however (where all tests are passing without issue)...

**Comment by crwood** [comment]
After further debugging on another, older Mac (on which I _was_ able to reproduce the failure), I've narrowed down the issue to inconsistent behavior observed by/with [this `iterate_downloader()` line](https://github.com/crwood/tahoe-lafs/blob/bc65dbd637d61aabfd6d433279d6bed80f5aaaa3/src/allmydata/test/test_magic_folder.py#L999). In my testing, awaiting on this deferred on a newer MacBook Air will consistently result in the creation of a ".conflict" file (and thus a passing test), whereas on the older iMac (and, I suspect, on Travis-CI), the ".conflict" file is created only _sometimes_ -- about 5%, in my testing (resulting in a failing test about 95% of the time).

To demonstrate, I [added some lines](https://github.com/tahoe-lafs/tahoe-lafs/pull/516/commits/d8c13ffc26bcfeac972f554a8ab9df3a7834f2cd) to print `bob_proc`, `os.path.exists(bob_fname + '.conflict')`, and `self.bob_magicfolder.downloader._hooks` both before and after awaiting on `iterate_downloader()`, with which Travis-CI shows the following output (as seen in the logs [here](https://travis-ci.org/tahoe-lafs/tahoe-lafs/jobs/408660892#L1365)), resulting in a failure:

```
################### before iterate_downloader(): ###################
<Deferred at 0x11269ab00>
False
{'inotify': None,
 'item_processed': None,
 'iteration': None,
 'processed': (<Deferred at 0x11269ab00>, 0),
 'started': (<Deferred at 0x1111cd5a8>, 0)}

################### after iterate_downloader(): ###################
<Deferred at 0x11269ab00>
False
{'inotify': None,
 'item_processed': None,
 'iteration': None,
 'processed': (<Deferred at 0x11269ab00>, 0),
 'started': (<Deferred at 0x1111cd5a8>, 0)}
```

On a local MacBook Air, however, the same test passes with the following output:

```
################### before iterate_downloader(): ###################
<Deferred at 0x10b3ecea8>
False
{'inotify': None,
 'item_processed': None,
 'iteration': None,
 'processed': (<Deferred at 0x10b3ecea8>, 0),
 'started': (<Deferred at 0x10b3cf638>, 0)}

################### after iterate_downloader(): ###################
<Deferred at 0x10b3ecea8 current result: True>
True
{'inotify': None,
 'item_processed': None,
 'iteration': None,
 'processed': None,
 'started': (<Deferred at 0x10b3cf638>, 0)}
```

To me, this suggests a race-condition _somewhere_ but, at this point, I'm not entirely sure where the crux of the problem lies... If anyone any advice on how to best proceed from here (or even input as to whether this test should just be skipped entirely on Travis-CI), I'd appreciate it!

**Comment by meejah** [comment]
It seems only the "mock" version of the test is failing -- so probably there's something wrong/different about how we're faking notify events on macos?

**Comment by exarkun** [comment]
The plan is now to switch all platforms over to using watchdog.  I'm attempting to accomplish that now.  If I succeed, I'll open a new PR and close this one.

**Comment by exarkun** [comment]
This basically landed in #558

**Pull request closed without merging**
