### PR TITLE
updated all python files to use pep-3110 exception syntax for python3 compatibility

### PR DESCRIPTION
**Pull request by heartsucker**
Fixes: https://tahoe-lafs.org/trac/tahoe-lafs/ticket/3013

---
This change is [Reviewable](https://reviewable.io/reviews/tahoe-lafs/tahoe-lafs/587)

### CODE REVIEW

**Comment by meejah** [comment]
@heartsucker needs a rebase I guess ...

**Comment by meejah** [comment]
Also circleci needs a kick (hung/non-responsive job?)

**Comment by heartsucker** [comment]
Hey @meejah I think this one can be merged since that codecov failure seems to be errant.

**Comment by meejah** [comment]
Hmmm, I wish github could tell me "what changed since I reviewed it last". Oh well :(

Also, @heartsucker would it be possible for you to idle in `#tahoe-lafs` for "not-quite-real-time chat/discussion"...?

**Pull request merged**
