### PR TITLE
2237.cloud backend s4 merged.3

### PR DESCRIPTION
**Pull request by meejah**

### CODE REVIEW

**Comment by meejah** [comment]
I don't understand why GitHub is sad about merging this; it's based on top of tahoe-lafs:2237.cloud-backend-s4-merged.0

**Comment by meejah** [comment]
Oh, I guess 2237.cloud-backend-s4-merged.0 got rebased yet again and my local ref was out of date

**Comment by meejah** [comment]
Ah, I see also @daira already added some of the same changes but w/o merging or something...

**Comment by daira** [comment]
Closing; 2237.cloud-backend-s4-merged.4 is now the current branch.

**Pull request closed without merging**
