### PR TITLE
3019 remove tuple unpacking

### PR DESCRIPTION
**Pull request by heartsucker**
Fixes: ticket:3019

https://tahoe-lafs.org/trac/tahoe-lafs/ticket/3019

---
This change is [Reviewable](https://reviewable.io/reviews/tahoe-lafs/tahoe-lafs/600)

### CODE REVIEW

**Comment by exarkun** [comment]
> fixes: 3019

This won't cause the ticket to close.  The merge commit message needs "Fixes: ticket:3019" in it.

**Comment by meejah** [comment]
Hrrmmmm...is there a "real error" there somewhere? I re-started the Travis job that failed on "too many open files" and it failed again, same error...

**Comment by meejah** [comment]
okay, it just failed a third time with too many open files ... oh, also it seems that one is failing on master too .. so nevermind

**Comment by heartsucker** [comment]
Can you kick the failed jobs when you get a chance?

**Pull request merged**
