### PR TITLE
Use 2.7-buster Docker image for pypy

### PR DESCRIPTION
**Pull request by sajith**
This should fix the failing PyPy CI job, such as [this](https://app.circleci.com/pipelines/github/tahoe-lafs/tahoe-lafs/60/workflows/21e74705-18c8-4af4-8326-5c8f3cf345ff/jobs/18760) one.

Related to [3299](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/3299).

---
This change is [Reviewable](https://reviewable.io/reviews/tahoe-lafs/tahoe-lafs/706)

### CODE REVIEW

**Comment by meejah** [comment]
It'll need a newsfragment to pass linter .. but also what happened to the circle-ci builds?

**Comment by sajith** [comment]
Added newfragment.  This time CircleCI is back in business.

**Comment by meejah** [comment]
Looks like the right stuff still isn't getting through to circle-ci's docker, anyway .. maybe re-starting the failed build is enough? (`meejahcircleci` user doesn't have enough permission to do that)

**Comment by exarkun** [comment]
> Looks like the right stuff still isn't getting through to circle-ci's docker, anyway .. maybe re-starting the failed build is enough? (`meejahcircleci` user doesn't have enough permission to do that)

It's on sajith's fork so I guess only sajith has permission to do that.

**Comment by exarkun** [comment]
I triggered a build of the pypy Docker image which succeeded - https://circleci.com/gh/tahoe-lafs/tahoe-lafs/18788 - so if the pypy job for this PR is re-run now, maybe it will succeed.

**Pull request merged**
