### PR TITLE
Make OneShotObserverList immediate

### PR DESCRIPTION
**Pull request by exarkun**
https://tahoe-lafs.org/trac/tahoe-lafs/ticket/3470

### CODE REVIEW

**Review by meejah — APPROVED** [review]
LGTM

I *would* like to understand the motivation behind ever using `eventually` here, though. My guess is it's probably something boring like "why not?".

**Comment by exarkun** [comment]
> LGTM
> 
> I _would_ like to understand the motivation behind ever using `eventually` here, though. My guess is it's probably something boring like "why not?".

I think it has to do with predictability and "plan interference".  You would rather have your Deferreds _always_ fire later instead of sometimes firing now and sometimes firing later because in the latter case you might have to deal with two different execution paths.

That's all fine and such but if you aren't careful enough in doing this you ruin your ability to write coherent unit tests.  Fortunately the two different execution paths don't seem to make any difference in this case - apart from making it possible to write some good unit tests once it's possible for Deferreds to fire now.

**Comment by exarkun** [comment]
The above may or may not accurately reflect the original motivation here, I'm just guessing of course.  However, I did just notice that `when_fired` *doesn't* use `eventually` so this thing was _already_ sometimes-now-sometimes-later - which might explain why making some of the later cases into now cases didn't break anything.  Or maybe it was just luck.  Who knows.

**Comment by meejah** [comment]
Okay .. yeah I was just guessing too obviously.

**Pull request merged**
