### PR TITLE
Port control.py to Python 3

### PR DESCRIPTION
**Pull request by chadwhitacre**
https://tahoe-lafs.org/trac/tahoe-lafs/ticket/3605

### CODE REVIEW

**Comment by chadwhitacre** [comment]
# CI

https://app.circleci.com/pipelines/github/tahoe-lafs/tahoe-lafs/1867/workflows/8291fff4-ea54-46a7-bb93-76b61ac7ab2d/jobs/44237

```
test_filesystem - allmydata.test.test_system.SystemTest
Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
foolscap.tokens.RemoteException: <RemoteException around '[CopiedFailure instance: Traceback from remote host -- Traceback (most recent call last):
  File "/tmp/tahoe-lafs.tox/py27-coverage/lib/python2.7/site-packages/foolscap/eventual.py", line 26, in _turn
    cb(*args, **kwargs)
  File "/tmp/tahoe-lafs.tox/py27-coverage/lib/python2.7/site-packages/foolscap/broker.py", line 580, in doNextCall
    d.addCallback(self._callFinished, delivery)
  File "/tmp/tahoe-lafs.tox/py27-coverage/lib/python2.7/site-packages/twisted/internet/defer.py", line 322, in addCallback
    callbackKeywords=kw)
  File "/tmp/tahoe-lafs.tox/py27-coverage/lib/python2.7/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/tmp/tahoe-lafs.tox/py27-coverage/lib/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/tmp/tahoe-lafs.tox/py27-coverage/lib/python2.7/site-packages/foolscap/broker.py", line 627, in _callFinished
    methodSchema.checkResults(res, False) # may raise Violation
  File "/tmp/tahoe-lafs.tox/py27-coverage/lib/python2.7/site-packages/foolscap/remoteinterface.py", line 297, in checkResults
    self.responseConstraint.checkObject(results, inbound)
  File "/tmp/tahoe-lafs.tox/py27-coverage/lib/python2.7/site-packages/foolscap/slicers/dict.py", line 146, in checkObject
    self.keyConstraint.checkObject(key, inbound)
  File "/tmp/tahoe-lafs.tox/py27-coverage/lib/python2.7/site-packages/foolscap/constraint.py", line 220, in checkObject
    raise Violation("'%r' is not a bytestring" % (obj,))
foolscap.tokens.Violation: Violation (in return value of <allmydata.control.ControlServer object at 0x7fd3b12133d0>.get_memory_usage): ("'u'VmData'' is not a bytestring",)
]'>
```

# Local

```
(py27) $ gb
* 3605.port-control
  master
(py27) $ trial allmydata.test.test_system.SystemTest.test_filesystem
allmydata.test.test_system
  SystemTest
    test_filesystem ...                                                    [OK]

-------------------------------------------------------------------------------
Ran 1 tests in 53.894s

PASSED (successes=1)
(py27) $
```

# 🤔

**Comment by chadwhitacre** [comment]
Mediocre coverage, 65%:

```
Name                                                 Stmts   Miss Branch BrPart  Cover   Missing
------------------------------------------------------------------------------------------------
src/allmydata/control.py                               234     76     64      8    65%   9->12, 26-43, 46-47, 54-55, 57-61, 63, 65-66, 72, 75-106, 109-121, 131, 191->192, 192, 211-215, 216->217, 217, 228->229, 229-231, 232->233, 233-235, 257->258, 258, 259->260, 260, 283->286, 286-287
```

https://github.com/tahoe-lafs/tahoe-lafs/pull/977/checks?check_run_id=1830656860#step:9:3457
https://github.com/tahoe-lafs/tahoe-lafs/pull/977/checks?check_run_id=1830656900#step:9:3490

Still getting some failures in CI though, which is good. All the reds are related, [e.g.](https://app.circleci.com/pipelines/github/tahoe-lafs/tahoe-lafs/1874/workflows/77552898-884e-414c-9019-d739df0764d2/jobs/44350):

```
Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
foolscap.tokens.RemoteException: <RemoteException around '[CopiedFailure instance: Traceback from remote host -- Traceback (most recent call last):
  File "/tmp/tahoe-lafs.tox/py27-coverage/lib/python2.7/site-packages/foolscap/eventual.py", line 26, in _turn
    cb(*args, **kwargs)
  File "/tmp/tahoe-lafs.tox/py27-coverage/lib/python2.7/site-packages/foolscap/broker.py", line 580, in doNextCall
    d.addCallback(self._callFinished, delivery)
  File "/tmp/tahoe-lafs.tox/py27-coverage/lib64/python2.7/site-packages/twisted/internet/defer.py", line 322, in addCallback
    callbackKeywords=kw)
  File "/tmp/tahoe-lafs.tox/py27-coverage/lib64/python2.7/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/tmp/tahoe-lafs.tox/py27-coverage/lib64/python2.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/tmp/tahoe-lafs.tox/py27-coverage/lib/python2.7/site-packages/foolscap/broker.py", line 627, in _callFinished
    methodSchema.checkResults(res, False) # may raise Violation
  File "/tmp/tahoe-lafs.tox/py27-coverage/lib/python2.7/site-packages/foolscap/remoteinterface.py", line 297, in checkResults
    self.responseConstraint.checkObject(results, inbound)
  File "/tmp/tahoe-lafs.tox/py27-coverage/lib/python2.7/site-packages/foolscap/slicers/dict.py", line 146, in checkObject
    self.keyConstraint.checkObject(key, inbound)
  File "/tmp/tahoe-lafs.tox/py27-coverage/lib/python2.7/site-packages/foolscap/constraint.py", line 220, in checkObject
    raise Violation("'%r' is not a bytestring" % (obj,))
foolscap.tokens.Violation: Violation (in return value of <allmydata.control.ControlServer object at 0x7f6535a46c10>.get_memory_usage): ("'u'VmSize'' is not a bytestring",)
]'>
```

Not sure about the yellows ... 🤔

**Comment by chadwhitacre** [comment]
Rebased on master, picking up some relevant changes in #978.

**Review by itamarst — APPROVED** [review]
Thank you!

**Review by sajith — APPROVED** [review]

**Pull request merged**
