### PR TITLE
Install test plugins

### PR DESCRIPTION
**Pull request by exarkun**
Fixes: ticket:3029

---
This change is [Reviewable](https://reviewable.io/reviews/tahoe-lafs/tahoe-lafs/608)

### CODE REVIEW

**Comment by meejah** [comment]
Keeps failing on "too many open files" ... but why isn't the master build failing like that?

**Comment by meejah** [comment]
rebased

**Comment by exarkun** [comment]
Looks like "too many files" is related to recent EADDRINUSE "fixes".  https://github.com/tahoe-lafs/tahoe-lafs/pull/610 tries to address that.  It's wild that these apparently unrelated changes make that failure so much more common.  And the timeout problem is unrelated and addressed by https://github.com/tahoe-lafs/tahoe-lafs/pull/611

**Comment by exarkun** [comment]
My guess is that the macOS failure is due to the macOS buildbot slave having a too-old old version of something like pip, setuptools, or tox and running into a bug in one of those tools in combination with other more recent software/services.

It looks like the macOS buildbot slave has its environment managed manually and it probably hasn't been updated in some while.

**Pull request merged**
