### PR TITLE
Remove most of the usage of future

### PR DESCRIPTION
**Pull request by a-detiste**
A bit more tricky but still bearable.

### CODE REVIEW

**Comment by itamarst** [comment]
Going to finish this up/review.

**Comment by itamarst** [comment]
I broke it :(

**Review by itamarst — APPROVED** [review]

**Comment by itamarst** [comment]
@a-detiste Thank you so much for doing this!

**Comment by a-detiste** [comment]
I m on Holliday now. But enjoy redingote this on the phone.

**Pull request merged**
