### PR TITLE
Ask trial to run the test suite with two processes.

### PR DESCRIPTION
**Pull request by exarkun**
Fixes https://tahoe-lafs.org/trac/tahoe-lafs/ticket/2894

### CODE REVIEW

**Comment by warner** [comment]
Looks like windows can't do parallel `-j` tests. What if we put that argument in an environment variable, and set it in `.travis.yml`, but not in `.appveyor.yml`? It might be nice to have it set locally (if the developer is running on a platform that can handle it), but for now I guess you could just put a line in your `.bash_profile` or something.

**Comment by exarkun** [comment]
Yea... I noticed the appveyor failures earlier today, then spent a couple hours trying to wrestle the system (tox, mostly) into doing it conditionally based on platform ... and failed.

To add insult to injury, I eventually realized that `-j` probably also disables all of the coverage measurement (because it moves most of the interesting Python execution to a different process and I don't believe `coverage run ...` follows child processes without significant extra effort.

So this would need to be disabled on Linux, too, as that is where coverage is collected.

That still leaves OS X (afaict coverage is not collected there) but at this point I'm kinda meh on the whole thing.  It's a lot of effort and the _complete_ build will still take as long as it does now.

**Comment by warner** [comment]
ok, let's not push too hard to get travis to run faster, but maybe just an option that lets local developers get parallelism if they want, and if they don't need coverage

**Comment by exarkun** [comment]
Okay.  This adds `TAHOE_LAFS_TRIAL_ARGS` env var to control the arguments passed to trial by tox.  It also adds docs telling users how they can use this to make the test suite faster.

**Comment by warner** [comment]
looks good!

**Pull request merged**
